name: CI

on:
  push:
    branches:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Build Assets
        run: npm i && npm run build

      - name: Build Site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site/
      